name: crystally
version: 1.0.0
summary: Crystally
description: Blink Blink Application

confinement: strict
base: core18
grade: stable

slots:
  dbus-crystally:
    interface: dbus
    bus: session
    name: vn.haova.crystally
    
apps:
  crystally:
    command: crystally
    extensions: [flutter-master]
    plugs:
    - network
    slots:
      - dbus-crystally
parts:
  crystally:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
